### ISSUE TITLE
"Rubygems is unreachable" message

### ISSUE THREAD

**Issue by pivotal-globehealer** [pivotal/pulse#1]
I'd like to suggest that we remove the banner warnings. They seem to occur frequently. It's more noise than signal. Maybe the url changed? If rubygems is down, I'll probably discover it pretty quickly.

Ditto for heroku, github, and the other warning messages.

**Comment by nertzy** [comment]
Big :+1:

**Comment by carpeliam** [comment]
The implementation that is live in most offices is https://github.com/pivotal/projectmonitor, this repository is a beach rewrite. While we'd love some commits that helps you get closer to this issue, I think you might want to raise this discussion there!
